import React, { useState, useMemo } from 'react';
import { 
  FileText, Plus, Clock, CheckCircle2, XCircle, 
  Download, Send, AlertTriangle, Sparkles,
  ShieldCheck, Lock, Check, X,
  Building2, Eye, RefreshCcw, Search, Calendar,
  HelpCircle, ExternalLink, Loader2,
  FileSignature, Shield
} from 'lucide-react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '@shared/lib/api';
import { toast } from 'sonner';
import { cn } from '@shared/lib/utils';
import { useAuthStore } from '@stores/authStore';

export default function StudentGuichetPage() {
  const queryClient = useQueryClient();
  const { user } = useAuthStore();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [filterStatus, setFilterStatus] = useState<'all' | 'ready' | 'pending' | 'rejected'>('all');
  const [searchQuery, setSearchQuery] = useState('');

  // Official PDF Preview Modal states (matches Admin parity)
  const [isPreviewModalOpen, setIsPreviewModalOpen] = useState(false);
  const [previewPdfBlobUrl, setPreviewPdfBlobUrl] = useState<string | null>(null);
  const [previewDocTitle, setPreviewDocTitle] = useState<string>('');
  const [previewLoadingId, setPreviewLoadingId] = useState<number | null>(null);
  const [downloadLoadingId, setDownloadLoadingId] = useState<number | null>(null);

  const [newRequestData, setNewRequestData] = useState({ 
    type: 'Attestation de Scolarité', 
    motif: '' 
  });

  const currentDate = new Date().toLocaleDateString('fr-FR', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // 1. Fetch live document requests from backend
  const { data: fetchRes, isLoading, refetch, isFetching } = useQuery({
    queryKey: ['student-document-requests'],
    queryFn: async () => {
      try {
        const res = await api.get('/student-portal/document-requests');
        return res.data;
      } catch {
        return null;
      }
    },
    staleTime: 30000,
  });

  // 2. Map types to official document_type_id in database
  const docTypeMap: Record<string, number> = {
    'Attestation de Scolarité': 1,
    'Relevé de Notes': 2,
    'Relevé de Notes (S1-S4)': 2,
    'Convention de Stage': 3,
    'Convention de Stage PFE': 3,
    'Attestation de Réussite': 4,
    'Attestation d\'Inscription': 5,
  };

  // 3. Mutation to submit request
  const requestMutation = useMutation({
    mutationFn: async (reqData: any) => {
      const payload = {
        document_type_id: docTypeMap[reqData.type] || 1,
        type: reqData.type,
        motif: reqData.motif,
      };
      const res = await api.post('/student-portal/document-requests', payload);
      return res.data;
    },
    onSuccess: () => {
      toast.success('Demande enregistrée avec succès au Service des Affaires Étudiantes !');
      setIsModalOpen(false);
      setNewRequestData({ type: 'Attestation de Scolarité', motif: '' });
      queryClient.invalidateQueries({ queryKey: ['student-document-requests'] });
    },
    onError: (error: any) => {
      toast.error(error?.response?.data?.message || 'Erreur lors de la soumission de la demande.');
    }
  });

  const requests: any[] = fetchRes?.data || [];

  // Computed metrics
  const totalCount = requests.length;
  const readyCount = requests.filter((r: any) => r.status === 'approved' || r.status === 'ready' || r.status === 'collected' || r.status === 'withdrawn').length;
  const pendingCount = requests.filter((r: any) => r.status === 'pending' || !r.status).length;
  const rejectedCount = requests.filter((r: any) => r.status === 'rejected').length;

  // Filtered list
  const filteredRequests = useMemo(() => {
    return requests.filter((req: any) => {
      const isCollected = req.status === 'collected' || req.status === 'withdrawn';
      const isApproved = req.status === 'approved' || req.status === 'ready' || isCollected;
      const isRejected = req.status === 'rejected';
      const isPending = !isApproved && !isRejected;

      if (filterStatus === 'ready' && !isApproved) return false;
      if (filterStatus === 'pending' && !isPending) return false;
      if (filterStatus === 'rejected' && !isRejected) return false;

      if (searchQuery.trim()) {
        const title = (req.document_type || req.type || '').toLowerCase();
        const idStr = String(req.id || '');
        const query = searchQuery.toLowerCase();
        return title.includes(query) || idStr.includes(query);
      }

      return true;
    });
  }, [requests, filterStatus, searchQuery]);

  // Preview official certified PDF (Identical to Admin)
  const handlePreviewDocument = async (req: any) => {
    try {
      setPreviewLoadingId(req.id);
      const title = req.document_type || req.type || 'Attestation de Scolarité';
      setPreviewDocTitle(title);
      toast.loading(`Préparation de l'aperçu certifié (${title})...`, { id: 'pdf-stream' });

      // Fetch authentic official PDF generated by DocumentRequestService
      const res = await api.get(`/student-portal/document-requests/${req.id}/preview`, {
        responseType: 'blob',
      });

      const blob = new Blob([res.data], { type: 'application/pdf' });
      const blobUrl = window.URL.createObjectURL(blob);
      setPreviewPdfBlobUrl(blobUrl);
      setIsPreviewModalOpen(true);
      toast.success('Document officiel certifié prêt pour consultation !', { id: 'pdf-stream' });
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Erreur lors du chargement de l\'aperçu du document.', { id: 'pdf-stream' });
    } finally {
      setPreviewLoadingId(null);
    }
  };

  // Download official certified PDF
  const handleDownloadDocument = async (req: any) => {
    try {
      setDownloadLoadingId(req.id);
      const title = req.document_type || req.type || 'Attestation_Scolarite';
      toast.loading(`Téléchargement de ${title}...`, { id: 'pdf-download' });

      const res = await api.get(`/student-portal/document-requests/${req.id}/download`, {
        responseType: 'blob',
      });

      const blob = new Blob([res.data], { type: 'application/pdf' });
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = blobUrl;
      const cleanName = title.replace(/\s+/g, '_');
      const studentName = user?.name ? user.name.replace(/\s+/g, '_') : 'ENCG_Fes';
      link.download = `${cleanName}_${studentName}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setTimeout(() => window.URL.revokeObjectURL(blobUrl), 10000);
      toast.success('Document officiel certifié téléchargé avec succès !', { id: 'pdf-download' });
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Erreur lors du téléchargement du document.', { id: 'pdf-download' });
    } finally {
      setDownloadLoadingId(null);
    }
  };

  const closePreviewModal = () => {
    setIsPreviewModalOpen(false);
    if (previewPdfBlobUrl) {
      window.URL.revokeObjectURL(previewPdfBlobUrl);
      setPreviewPdfBlobUrl(null);
    }
  };

  return (
    <div data-testid="student-guichet-page" className="space-y-6 font-sans animate-in fade-in duration-500 text-slate-900 dark:text-slate-100 pb-20">
      
      {/* ── Executive Top Header ── */}
      <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-4 border-b border-slate-200/80 dark:border-slate-800 pb-5">
        <div className="space-y-1.5">
          <div className="flex flex-wrap items-center gap-2.5">
            <h1 className="text-xl sm:text-2xl lg:text-3xl font-black tracking-tight text-[#001A4B] dark:text-white">
              Guichet Unique & Coffre-Fort Numérique
            </h1>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[11px] font-bold bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border border-emerald-500/20 shadow-2xs">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              Service Scolarité Actif
            </span>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium flex items-center gap-2 flex-wrap">
            <Building2 className="w-3.5 h-3.5 text-slate-400 shrink-0" />
            <span>École Nationale de Commerce et de Gestion de Fès</span>
            <span className="text-slate-300 dark:text-slate-700 hidden sm:inline">•</span>
            <span>Délivrance 100% en Ligne</span>
            <span className="text-slate-300 dark:text-slate-700 hidden sm:inline">•</span>
            <span className="font-semibold text-slate-700 dark:text-slate-300 capitalize">{currentDate}</span>
          </p>
        </div>

        {/* Action Toolbar */}
        <div className="flex items-center gap-2 shrink-0">
          <button
            onClick={() => refetch()}
            disabled={isFetching}
            className="inline-flex items-center justify-center gap-2 h-10 px-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs font-bold text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 hover:border-slate-300 transition-all cursor-pointer disabled:opacity-50 shadow-2xs"
            title="Rafraîchir les demandes"
          >
            <RefreshCcw className={cn("w-3.5 h-3.5 text-slate-500", isFetching && "animate-spin text-blue-600")} />
            <span className="hidden sm:inline">Actualiser</span>
          </button>

          <button
            onClick={() => setIsModalOpen(true)}
            className="inline-flex items-center justify-center gap-2 h-10 px-4.5 rounded-xl bg-[#001A4B] hover:bg-[#082663] text-white text-xs font-bold shadow-sm hover:shadow-md transition-all cursor-pointer border border-white/10"
          >
            <Plus className="w-4 h-4 text-amber-300" />
            <span>Nouvelle Demande</span>
          </button>
        </div>
      </div>

      {/* ── Executive Hero Banner ── */}
      <div className="relative overflow-hidden rounded-2xl sm:rounded-3xl bg-gradient-to-br from-[#001A4B] via-[#082663] to-[#001338] text-white p-5 sm:p-7 lg:p-8 shadow-xl border border-blue-900/40">
        <div className="absolute top-0 right-0 w-80 sm:w-96 h-80 sm:h-96 bg-blue-500/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20" />
        <div className="absolute bottom-0 left-1/3 w-64 sm:w-80 h-64 sm:h-80 bg-amber-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 flex flex-col lg:flex-row items-stretch lg:items-center justify-between gap-6">
          {/* Left Column: Heading & Trust Badges */}
          <div className="space-y-4 max-w-2xl flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider bg-amber-400/15 text-amber-300 border border-amber-400/30">
                <ShieldCheck className="w-3.5 h-3.5 text-amber-300" />
                Guichet Numérique Certifié
              </span>
              <span className="px-3 py-1 rounded-lg text-[10px] font-bold tracking-wide bg-white/10 text-blue-100 border border-white/15">
                Signature Cryptographique SHA-256
              </span>
            </div>

            <div>
              <h2 className="text-xl sm:text-2xl lg:text-3xl font-black tracking-tight text-white flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-white/10 border border-white/20 flex items-center justify-center text-amber-300 shrink-0">
                  <FileSignature className="w-5 h-5" />
                </div>
                <span>Mes Demandes & Coffre-Fort Électronique</span>
              </h2>
              <p className="mt-1.5 text-xs sm:text-sm text-blue-200/80 font-normal leading-relaxed">
                Effectuez vos demandes de pièces administratives (Attestation de scolarité, Relevé de notes, etc.) sans déplacement. Suivez l'instruction de votre dossier et téléchargez vos documents certifiés avec QR Code officiel.
              </p>
            </div>

            {/* Quick Badges Row */}
            <div className="flex flex-wrap items-center gap-2 pt-1 text-xs">
              <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-white/[0.06] border border-white/10 text-blue-200 font-medium">
                <Clock className="w-3.5 h-3.5 text-amber-400" />
                <span>Délai moyen d'instruction : <strong>24h à 48h</strong></span>
              </div>
              <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-white/[0.06] border border-white/10 text-blue-200 font-medium">
                <Shield className="w-3.5 h-3.5 text-emerald-400" />
                <span>Validité juridique garantie</span>
              </div>
            </div>
          </div>

          {/* Right Column: Glassmorphism KPI Stats Pod */}
          <div className="w-full lg:w-72 bg-white/[0.07] backdrop-blur-xl p-4 sm:p-5 rounded-2xl border border-white/15 shadow-xl flex flex-col justify-between shrink-0">
            <div className="text-[11px] font-bold uppercase tracking-wider text-blue-300 pb-3 border-b border-white/10 flex items-center justify-between">
              <span>Statut des Demandes</span>
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
            </div>

            <div className="grid grid-cols-3 gap-2 py-3.5 text-center">
              <div>
                <div className="text-xl sm:text-2xl font-black text-white">{totalCount}</div>
                <div className="text-[9.5px] font-bold uppercase tracking-wide text-blue-200 mt-1 leading-tight">Total Déposé</div>
              </div>
              <div className="border-x border-white/10 px-1">
                <div className="text-xl sm:text-2xl font-black text-emerald-300">{readyCount}</div>
                <div className="text-[9.5px] font-bold uppercase tracking-wide text-blue-200 mt-1 leading-tight">Prêts / Validés</div>
              </div>
              <div>
                <div className="text-xl sm:text-2xl font-black text-amber-300">{pendingCount}</div>
                <div className="text-[9.5px] font-bold uppercase tracking-wide text-blue-200 mt-1 leading-tight">En Instruction</div>
              </div>
            </div>

            <div className="pt-2.5 border-t border-white/10 flex items-center justify-between text-[11px] text-blue-200/80 font-medium">
              <span>Coffre-Fort : <strong className="text-emerald-400">Actif</strong></span>
              <span className="font-mono text-[10px] text-slate-300">SHA-256</span>
            </div>
          </div>
        </div>
      </div>

      {/* ── Filters & Search Toolbar ── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white dark:bg-slate-900 p-3 sm:p-4 rounded-2xl border border-slate-200/80 dark:border-slate-800 shadow-2xs">
        {/* Status Filter Tabs */}
        <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800/80 p-1 rounded-xl overflow-x-auto w-full sm:w-auto">
          <button
            onClick={() => setFilterStatus('all')}
            className={cn(
              "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer shrink-0",
              filterStatus === 'all'
                ? "bg-[#001A4B] text-white shadow-xs"
                : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
            )}
          >
            <span>Toutes</span>
            <span className={cn("px-1.5 py-0.2 rounded-md text-[10px]", filterStatus === 'all' ? "bg-white/20 text-white" : "bg-slate-200 dark:bg-slate-700 text-slate-600")}>
              {totalCount}
            </span>
          </button>

          <button
            onClick={() => setFilterStatus('ready')}
            className={cn(
              "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer shrink-0",
              filterStatus === 'ready'
                ? "bg-[#001A4B] text-white shadow-xs"
                : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
            )}
          >
            <span>Prêtes au Coffre-Fort</span>
            <span className={cn("px-1.5 py-0.2 rounded-md text-[10px]", filterStatus === 'ready' ? "bg-white/20 text-white" : "bg-emerald-100 text-emerald-800")}>
              {readyCount}
            </span>
          </button>

          <button
            onClick={() => setFilterStatus('pending')}
            className={cn(
              "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer shrink-0",
              filterStatus === 'pending'
                ? "bg-[#001A4B] text-white shadow-xs"
                : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
            )}
          >
            <span>En cours</span>
            <span className={cn("px-1.5 py-0.2 rounded-md text-[10px]", filterStatus === 'pending' ? "bg-white/20 text-white" : "bg-amber-100 text-amber-800")}>
              {pendingCount}
            </span>
          </button>

          {rejectedCount > 0 && (
            <button
              onClick={() => setFilterStatus('rejected')}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer shrink-0",
                filterStatus === 'rejected'
                  ? "bg-[#001A4B] text-white shadow-xs"
                  : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
              )}
            >
              <span>Non accordées</span>
              <span className={cn("px-1.5 py-0.2 rounded-md text-[10px]", filterStatus === 'rejected' ? "bg-white/20 text-white" : "bg-rose-100 text-rose-800")}>
                {rejectedCount}
              </span>
            </button>
          )}
        </div>

        {/* Search & Counter */}
        <div className="flex items-center gap-2.5 w-full sm:w-auto">
          <div className="relative flex-1 sm:w-64">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Rechercher une pièce..."
              className="w-full pl-8 pr-3 py-1.5 text-xs bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20"
            />
          </div>
          <span className="text-xs font-semibold text-slate-400 shrink-0 hidden sm:inline">
            {filteredRequests.length} demande(s)
          </span>
        </div>
      </div>

      {/* ── Document Requests List ── */}
      <div className="space-y-4">
        {isLoading ? (
          <div className="bg-white dark:bg-slate-900 rounded-3xl p-12 text-center border border-slate-200 dark:border-slate-800">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#001A4B] mx-auto" />
            <p className="text-xs text-slate-400 mt-3 font-semibold">Chargement de votre coffre-fort numérique...</p>
          </div>
        ) : filteredRequests.length === 0 ? (
          <div className="bg-white dark:bg-slate-900 rounded-3xl p-12 text-center shadow-sm border border-slate-200 dark:border-slate-800 space-y-3">
            <FileText className="w-12 h-12 text-slate-300 dark:text-slate-600 mx-auto" />
            <h3 className="text-base font-black text-slate-800 dark:text-slate-100">Aucune demande trouvée</h3>
            <p className="text-xs text-slate-500 max-w-md mx-auto">
              {searchQuery ? "Aucune pièce administrative ne correspond à votre recherche." : "Vous n'avez aucune demande active dans cette catégorie."}
            </p>
            <button
              onClick={() => setIsModalOpen(true)}
              className="inline-flex items-center gap-2 h-10 px-5 rounded-xl bg-[#001A4B] text-white text-xs font-bold shadow-sm hover:shadow-md transition-all cursor-pointer mt-2"
            >
              <Plus className="w-4 h-4 text-amber-300" />
              <span>Créer une nouvelle demande</span>
            </button>
          </div>
        ) : (
          filteredRequests.map((req: any) => {
            const isCollected = req.status === 'collected' || req.status === 'withdrawn';
            const isApproved = req.status === 'approved' || req.status === 'ready' || isCollected;
            const isRejected = req.status === 'rejected';
            const step = isApproved ? 3 : isRejected ? 2 : 2;

            const docTitle = req.document_type || req.type || (
              req.document_type_id === 1 ? 'Attestation de Scolarité' :
              req.document_type_id === 2 ? 'Relevé de Notes' :
              req.document_type_id === 3 ? 'Convention de Stage PFE' :
              req.document_type_id === 4 ? 'Attestation de Réussite' :
              req.document_type_id === 5 ? 'Attestation d\'Inscription' :
              `Document #${req.id}`
            );
            
            const rawDate = req.requested_at || req.created_at;
            const formattedDate = rawDate 
              ? new Date(rawDate).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })
              : 'Date récente';

            return (
              <div 
                key={req.id} 
                className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-3xl p-5 sm:p-6 shadow-2xs hover:shadow-md transition-all space-y-5"
              >
                {/* Header: Document Title, Reference, Status Badge */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div className="flex items-center gap-3.5">
                    <div className={cn(
                      "w-12 h-12 rounded-2xl flex items-center justify-center font-black text-xl shadow-sm shrink-0",
                      isApproved ? "bg-emerald-500/10 text-emerald-600 border border-emerald-500/20" :
                      isRejected ? "bg-rose-500/10 text-rose-600 border border-rose-500/20" :
                      "bg-amber-500/10 text-amber-600 border border-amber-500/20"
                    )}>
                      <FileText className="w-6 h-6" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2 flex-wrap">
                        <h3 className="font-black text-base sm:text-lg text-slate-900 dark:text-white leading-tight">
                          {docTitle}
                        </h3>
                        <span className="px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-[10px] font-mono font-bold text-slate-500">
                          Réf: #{req.id}
                        </span>
                      </div>
                      <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-1 flex items-center gap-2">
                        <Calendar className="w-3.5 h-3.5 text-slate-400" />
                        <span>Transmise le {formattedDate}</span>
                        {req.processed_at && (
                          <>
                            <span className="text-slate-300 dark:text-slate-700">•</span>
                            <span>Traitée le {new Date(req.processed_at).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' })}</span>
                          </>
                        )}
                      </p>
                    </div>
                  </div>

                  {/* Status Badge */}
                  <div className="shrink-0">
                    {isApproved ? (
                      <span className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-bold bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border border-emerald-500/20 shadow-2xs">
                        <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                        Document Prêt dans le Coffre-Fort
                      </span>
                    ) : isRejected ? (
                      <span className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-bold bg-rose-500/10 text-rose-700 dark:text-rose-400 border border-rose-500/20 shadow-2xs">
                        <XCircle className="w-4 h-4 text-rose-500" />
                        Demande Non Accordée
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-bold bg-amber-500/10 text-amber-700 dark:text-amber-400 border border-amber-500/20 shadow-2xs">
                        <Clock className="w-4 h-4 text-amber-500 animate-pulse" />
                        En cours de traitement scolarité
                      </span>
                    )}
                  </div>
                </div>

                {/* Motif / Raison (If provided) */}
                {req.motif && (
                  <div className="p-3 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-100 dark:border-slate-800 text-xs text-slate-600 dark:text-slate-300">
                    <span className="font-bold text-slate-700 dark:text-slate-200">Motif déclaré :</span> {req.motif}
                  </div>
                )}

                {/* Motif de Refus Officiel (Visible dès que la demande est rejetée) */}
                {isRejected && (
                  <div className="p-4 bg-rose-50/90 dark:bg-rose-950/40 rounded-2xl border border-rose-200 dark:border-rose-900/50 text-xs text-rose-900 dark:text-rose-100 flex items-start gap-3 shadow-2xs">
                    <div className="w-8 h-8 rounded-xl bg-rose-100 dark:bg-rose-900/60 text-rose-600 flex items-center justify-center shrink-0 mt-0.5 shadow-2xs">
                      <AlertTriangle className="w-4 h-4" />
                    </div>
                    <div className="space-y-1 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <strong className="text-[11px] font-black uppercase text-rose-800 dark:text-rose-300 tracking-wide">
                          Motif du Refus de l'Administration :
                        </strong>
                        <span className="px-2 py-0.5 rounded-full bg-rose-200/60 dark:bg-rose-900/60 text-rose-800 dark:text-rose-200 text-[10px] font-bold">
                          Dossier non validé
                        </span>
                      </div>
                      <p className="text-xs text-rose-950 dark:text-rose-100 font-medium leading-relaxed">
                        {req.admin_notes || "Dossier administratif non conforme ou pièce justificative manquante. Veuillez vérifier les informations de votre demande ou vous rapprocher du Service des Affaires Étudiantes."}
                      </p>
                    </div>
                  </div>
                )}

                {/* Sleek Institutional Progress Stepper */}
                <div className="py-2 px-2 sm:px-4 bg-slate-50/60 dark:bg-slate-800/30 rounded-2xl border border-slate-100 dark:border-slate-800">
                  <div className="flex items-center justify-between text-[11px] font-bold text-slate-400 mb-3">
                    <span>Circuit d'instruction officiel</span>
                    <span className="text-slate-500 font-medium hidden sm:inline">Délai indicatif moyen : 24h</span>
                  </div>
                  <div className="relative flex items-center justify-between">
                    {/* Stepper Track */}
                    <div className="absolute left-0 top-1/2 -translate-y-1/2 w-full h-1 bg-slate-200 dark:bg-slate-700 rounded-full z-0" />
                    <div
                      className={cn(
                        "absolute left-0 top-1/2 -translate-y-1/2 h-1 rounded-full transition-all duration-500 z-0",
                        isApproved ? "bg-emerald-500 w-full" : isRejected ? "bg-rose-500 w-1/2" : "bg-amber-500 w-1/2"
                      )}
                    />

                    {/* Step 1: Dépôt */}
                    <div className="relative z-10 flex flex-col items-center gap-1.5 text-center bg-slate-50/60 dark:bg-slate-800/30 px-1">
                      <div className="w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center text-xs font-black bg-emerald-600 text-white shadow-sm">
                        <Check className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                      </div>
                      <span className="text-[10px] sm:text-[11px] font-bold text-slate-800 dark:text-slate-200">
                        1. Dépôt Initial
                      </span>
                    </div>

                    {/* Step 2: Instruction */}
                    <div className="relative z-10 flex flex-col items-center gap-1.5 text-center bg-slate-50/60 dark:bg-slate-800/30 px-1">
                      <div className={cn(
                        "w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center text-xs font-black shadow-sm transition-all",
                        isApproved ? "bg-emerald-600 text-white" :
                        isRejected ? "bg-rose-600 text-white" :
                        "bg-amber-500 text-white animate-pulse"
                      )}>
                        {isApproved ? <Check className="w-3.5 h-3.5 sm:w-4 sm:h-4" /> :
                         isRejected ? <X className="w-3.5 h-3.5 sm:w-4 sm:h-4" /> :
                         <Clock className="w-3.5 h-3.5 sm:w-4 sm:h-4" />}
                      </div>
                      <span className={cn(
                        "text-[10px] sm:text-[11px] font-bold",
                        isRejected ? "text-rose-600" : isApproved ? "text-slate-800 dark:text-slate-200" : "text-amber-600 dark:text-amber-400"
                      )}>
                        {isRejected ? '2. Rejeté' : isApproved ? '2. Contrôle Scolarité' : '2. En Contrôle'}
                      </span>
                    </div>

                    {/* Step 3: Délivrance */}
                    <div className="relative z-10 flex flex-col items-center gap-1.5 text-center bg-slate-50/60 dark:bg-slate-800/30 px-1">
                      <div className={cn(
                        "w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center text-xs font-black shadow-sm transition-all",
                        isApproved ? "bg-emerald-600 text-white shadow-emerald-500/20" :
                        "bg-white dark:bg-slate-800 border-2 border-slate-300 dark:border-slate-600 text-slate-400"
                      )}>
                        {isApproved ? <ShieldCheck className="w-3.5 h-3.5 sm:w-4 sm:h-4" /> : '3'}
                      </div>
                      <span className={cn(
                        "text-[10px] sm:text-[11px] font-bold",
                        isApproved ? "text-emerald-700 dark:text-emerald-400" : "text-slate-400"
                      )}>
                        3. Signé & QR Certifié
                      </span>
                    </div>
                  </div>
                </div>

                {/* Footer: Actions & Cryptographic Integrity */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2 border-t border-slate-100 dark:border-slate-800">
                  <div className="flex items-center gap-2 font-mono text-[10px] text-slate-500 bg-slate-100 dark:bg-slate-800/80 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 w-fit">
                    <Lock className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                    <span>Empreinte SHA-256 : {req.hash ? req.hash.substring(0, 16) + '...' : 'e3b0c44298fc1c14...'}</span>
                  </div>

                  {/* Document Actions */}
                  <div className="flex items-center gap-2 self-end sm:self-auto">
                    {isApproved && (
                      <>
                        <button
                          onClick={() => handlePreviewDocument(req)}
                          disabled={previewLoadingId === req.id}
                          className="inline-flex items-center gap-1.5 h-9 px-3.5 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-bold transition-all cursor-pointer disabled:opacity-50"
                          title="Consulter l'exemplaire officiel certifié"
                        >
                          {previewLoadingId === req.id ? (
                            <Loader2 className="w-3.5 h-3.5 text-blue-600 animate-spin" />
                          ) : (
                            <Eye className="w-3.5 h-3.5 text-blue-600" />
                          )}
                          <span>Aperçu Document</span>
                        </button>

                        <button
                          onClick={() => handleDownloadDocument(req)}
                          disabled={downloadLoadingId === req.id}
                          className="inline-flex items-center gap-1.5 h-9 px-4 rounded-xl bg-[#001A4B] hover:bg-[#082663] text-white text-xs font-bold shadow-sm hover:shadow-md transition-all cursor-pointer border border-white/10 disabled:opacity-50"
                          title="Télécharger le fichier PDF officiel avec QR Code et Sceau"
                        >
                          {downloadLoadingId === req.id ? (
                            <Loader2 className="w-3.5 h-3.5 text-amber-300 animate-spin" />
                          ) : (
                            <Download className="w-3.5 h-3.5 text-amber-300" />
                          )}
                          <span>Télécharger PDF Officiel</span>
                        </button>
                      </>
                    )}

                    {!isApproved && !isRejected && (
                      <span className="text-xs font-semibold text-slate-400 italic">
                        Instruction en cours par le Service des Affaires Étudiantes.
                      </span>
                    )}
                  </div>
                </div>

              </div>
            );
          })
        )}
      </div>

      {/* ── Modal Nouvelle Demande (Redesigned) ── */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/75 backdrop-blur-md animate-in fade-in duration-200">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl w-full max-w-lg shadow-2xl overflow-hidden">
            {/* Modal Header */}
            <div className="p-5 sm:p-6 bg-gradient-to-r from-[#001A4B] via-[#082663] to-[#041438] text-white flex items-center justify-between">
              <div className="space-y-1">
                <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-white/10 text-amber-300 border border-white/15">
                  <Sparkles className="w-3 h-3" /> Guichet Unique 100% En Ligne
                </span>
                <h2 className="text-base sm:text-lg font-black tracking-tight text-white">
                  Nouvelle Demande de Pièce Officielle
                </h2>
              </div>
              <button 
                onClick={() => setIsModalOpen(false)} 
                className="w-8 h-8 flex items-center justify-center rounded-xl bg-white/10 hover:bg-white/20 text-slate-300 hover:text-white transition-all cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Modal Form */}
            <form 
              onSubmit={(e) => { 
                e.preventDefault(); 
                requestMutation.mutate(newRequestData); 
              }} 
              className="p-5 sm:p-6 space-y-4"
            >
              <div>
                <label className="block text-xs font-black uppercase text-slate-500 tracking-wider mb-2">
                  Sélectionnez le Document Souhaité *
                </label>
                <select
                  value={newRequestData.type}
                  onChange={(e) => setNewRequestData(p => ({ ...p, type: e.target.value }))}
                  className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-800 text-xs font-bold text-slate-800 dark:text-slate-200 focus:ring-2 focus:ring-[#001A4B] focus:border-transparent outline-none cursor-pointer"
                >
                  <option value="Attestation de Scolarité">Attestation de Scolarité (Année universitaire 2026-2027)</option>
                  <option value="Relevé de Notes (S1-S4)">Relevé de Notes Officiel (Semestres Validés)</option>
                  <option value="Convention de Stage PFE">Convention de Stage PFE / Stage d'Initiation</option>
                  <option value="Attestation de Réussite">Attestation de Réussite de Niveau</option>
                  <option value="Attestation d'Inscription">Attestation d'Inscription & Récépissé</option>
                </select>
                <p className="text-[11px] text-slate-400 mt-1.5 font-medium">
                  Le document sera certifié numériquement avec QR Code d'authenticité et empreinte cryptographique SHA-256.
                </p>
              </div>

              <div>
                <label className="block text-xs font-black uppercase text-slate-500 tracking-wider mb-2">
                  Motif & Organisme Destinataire *
                </label>
                <textarea
                  required
                  rows={3}
                  value={newRequestData.motif}
                  onChange={(e) => setNewRequestData(p => ({ ...p, motif: e.target.value }))}
                  placeholder="Ex: Candidature stage PFE, renouvellement carte séjour, dossier de bourse ou visa..."
                  className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-800 text-xs font-medium text-slate-800 dark:text-slate-200 focus:ring-2 focus:ring-[#001A4B] focus:border-transparent outline-none resize-none"
                />
              </div>

              {/* Notice Box */}
              <div className="p-3 bg-blue-50 dark:bg-blue-950/40 rounded-xl border border-blue-200 dark:border-blue-900/50 text-xs text-blue-900 dark:text-blue-200 flex items-start gap-2">
                <HelpCircle className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
                <span className="text-[11px] leading-relaxed">
                  Votre demande sera transmise immédiatement au Service Scolarité de l'ENCG Fès. Vous recevrez une notification par email dès que le document sera disponible dans votre coffre-fort.
                </span>
              </div>

              {/* Footer Actions */}
              <div className="flex items-center justify-end gap-2.5 pt-3 border-t border-slate-100 dark:border-slate-800">
                <button 
                  type="button" 
                  onClick={() => setIsModalOpen(false)} 
                  className="px-4 py-2 text-xs font-bold text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl cursor-pointer"
                >
                  Annuler
                </button>
                <button 
                  type="submit" 
                  disabled={requestMutation.isPending}
                  className="inline-flex items-center gap-2 px-5 py-2.5 text-xs font-bold bg-[#001A4B] hover:bg-[#082663] text-white rounded-xl shadow-sm transition-all cursor-pointer disabled:opacity-50"
                >
                  {requestMutation.isPending ? (
                    <>
                      <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      <span>Envoi en cours...</span>
                    </>
                  ) : (
                    <>
                      <Send className="w-3.5 h-3.5 text-amber-300" />
                      <span>Soumettre la demande</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ── Modal Aperçu Document PDF Officiel (Exactement identique à l'Administration) ── */}
      {isPreviewModalOpen && previewPdfBlobUrl && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 md:p-6 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl sm:rounded-3xl w-full max-w-5xl h-[92vh] flex flex-col shadow-2xl overflow-hidden">
            {/* Modal Header */}
            <div className="px-4 py-3.5 sm:px-6 sm:py-4 bg-[#001A4B] text-white flex items-center justify-between gap-3 shrink-0 border-b border-white/10">
              <div className="flex items-center gap-3 min-w-0">
                <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center shrink-0 border border-white/15">
                  <ShieldCheck className="w-5 h-5 text-emerald-400" />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h2 className="text-sm sm:text-base font-black tracking-tight truncate text-white">
                      {previewDocTitle}
                    </h2>
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                      <Check className="w-3 h-3" /> Certifié Conforme
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-300 truncate">
                    École Nationale de Commerce et de Gestion de Fès • Document Officiel Sécurisé
                  </p>
                </div>
              </div>

              {/* Header Action Buttons */}
              <div className="flex items-center gap-1.5 sm:gap-2 shrink-0">
                <button
                  type="button"
                  onClick={() => window.open(previewPdfBlobUrl, '_blank')}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-bold transition-all cursor-pointer border border-white/10"
                  title="Ouvrir dans un nouvel onglet"
                >
                  <ExternalLink className="w-3.5 h-3.5 text-blue-300" />
                  <span className="hidden md:inline">Nouvel onglet</span>
                </button>

                <a
                  href={previewPdfBlobUrl}
                  download={`${previewDocTitle.replace(/\s+/g, '_')}_ENCG.pdf`}
                  className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-amber-400 hover:bg-amber-300 text-slate-900 text-xs font-black shadow-sm transition-all cursor-pointer"
                  title="Télécharger le fichier PDF officiel"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Télécharger</span>
                </a>

                <button
                  type="button"
                  onClick={closePreviewModal}
                  className="w-8 h-8 rounded-xl bg-white/10 hover:bg-rose-500 text-slate-300 hover:text-white transition-all flex items-center justify-center cursor-pointer ml-1"
                  title="Fermer l'aperçu"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Modal Body: Direct Streamed Certified PDF Preview */}
            <div className="flex-1 w-full bg-slate-100 dark:bg-slate-950 p-1 sm:p-3 overflow-hidden">
              <iframe
                src={`${previewPdfBlobUrl}#toolbar=1&navpanes=0`}
                title={`Aperçu PDF - ${previewDocTitle}`}
                className="w-full h-full rounded-xl border border-slate-200 dark:border-slate-800 shadow-inner bg-white"
              />
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
