<?php

namespace App\Services\Academic;

use App\Models\AttendanceSession;
use App\Models\AttendanceRecord;
use App\Models\StudentModuleReservation;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class AttendanceService
{
    /**
     * Start a new attendance session and generate initial absent records.
     */
    public function startSession(int $moduleId, int $groupId, int $professorId, string $roomName): AttendanceSession
    {
        return DB::transaction(function () use ($moduleId, $groupId, $professorId, $roomName) {
            $session = AttendanceSession::create([
                'module_id' => $moduleId,
                'group_id' => $groupId,
                'professor_id' => $professorId,
                'room_name' => $roomName,
                'session_date' => Carbon::today(),
                'start_time' => Carbon::now(),
                'status' => 'active',
                // qr_token will be generated by Model events or factory if needed
                'qr_token' => \Illuminate\Support\Str::uuid(),
            ]);

            // Pre-fill attendance_records as 'absent' for all students in the group
            // SARGable query: get students registered to this module/group
            $studentIds = StudentModuleReservation::where('module_id', $moduleId)
                ->whereHas('student', function ($q) use ($groupId) {
                    $q->whereHas('pathways', function ($p) use ($groupId) {
                        $p->where('group_id', $groupId)->where('is_current', true);
                    });
                })->pluck('student_id');

            $records = [];
            $now = now();
            foreach ($studentIds as $studentId) {
                $records[] = [
                    'attendance_session_id' => $session->id,
                    'student_id' => $studentId,
                    'status' => 'absent',
                    'is_justified' => false,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }

            foreach (array_chunk($records, 500) as $chunk) {
                AttendanceRecord::insert($chunk);
            }

            return $session;
        });
    }

    /**
     * Mark a student's presence (via QR scan or manual).
     */
    public function markPresence(int $sessionId, int $studentId, string $status = 'present'): AttendanceRecord
    {
        $record = AttendanceRecord::firstOrCreate(
            ['attendance_session_id' => $sessionId, 'student_id' => $studentId],
            ['status' => 'absent', 'is_justified' => false]
        );

        $record->update([
            'status' => $status,
            'scanned_at' => Carbon::now(),
            'is_valid' => true,
        ]);

        return $record;
    }

    /**
     * Close the attendance session.
     */
    public function closeSession(int $sessionId): AttendanceSession
    {
        $session = AttendanceSession::findOrFail($sessionId);
        $session->update([
            'status' => 'completed',
            'end_time' => Carbon::now(),
            'qr_token' => null // invalidate QR
        ]);

        return $session;
    }
}
